---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $SERVICE_NAME
  labels:
    app: $SERVICE_NAME
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: $SERVICE_NAME
  template:
    metadata:
      name: $SERVICE_NAME
      labels:
        app: $SERVICE_NAME
        tier: web
    spec:
      hostAliases:
        - hostnames:
          - mongo-test-01
          ip: 10.141.10.150
        - hostnames:
          - mongo-test-02
          ip: 10.141.10.112
        - hostnames:
          - mongo-test-03
          ip: 10.141.10.125
      containers:
        - name: $SERVICE_NAME
          image: $BUILD_IMAGE
          resources:
            requests:
              memory: "1024Mi"
              cpu: "5"
            limits:
              memory: "2048Mi"
              cpu: "5"
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: environment-variables
          ports:
          - name: web
            containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3

